---
dist: bionic

language: c

matrix:
  include:
    - addons:
        apt:
          packages:
            - codespell
      env:
        - MAKEFLAGS=-j$(nproc)
      install:
        - git clone --depth 1 -b uncrustify-0.72.0
            https://github.com/uncrustify/uncrustify
        - mkdir -p uncrustify/build
        - (cd uncrustify/build && cmake -DCMAKE_INSTALL_PREFIX=$PWD
            -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 ..)
        - make -C uncrustify/build
        - export PATH=$PATH:$PWD/uncrustify/build
        - uncrustify --version
      name: Run source code checks
      script:
        - make check-format
        - codespell -i 0 -q 4 $(git ls-files)
    - addons:
        apt:
          packages:
            - doxygen
            - gcc-aarch64-linux-gnu
            - graphviz
            - libc6-dev-arm64-cross
      env:
        - CONFIGS="allnoconfig allyesconfig defconfig
                   bananapi_m2_plus_h3_defconfig
                   beelink_x2_defconfig
                   libretech_all_h3_cc_h3_defconfig
                   libretech_all_h3_cc_h5_defconfig
                   orangepi_3_defconfig
                   orangepi_one_defconfig
                   orangepi_pc2_defconfig
                   orangepi_plus2e_defconfig
                   orangepi_win_defconfig
                   orangepi_zero_plus_defconfig
                   pine64_plus_defconfig
                   pine_h64_defconfig
                   pinebook_defconfig
                   pinephone_defconfig
                   tanix_tx6_defconfig
                   tbs_a711_defconfig
                   randconfig randconfig randconfig"
        - GCC_VER=9.1.1-20190507
        - HOST_COMPILE=aarch64-linux-gnu-
        - MAKEFLAGS=-j$(nproc)
      install:
        - curl -LSs https://github.com/stffrdhrn/gcc/releases/download/or1k-$GCC_VER/or1k-linux-musl-$GCC_VER.tar.xz |
            tar xJf -
        - export PATH=$PATH:$PWD/or1k-linux-musl/bin
      name: Build all configs
      script:
        - |-
          set -e
          cd /tmp
          ln -s $TRAVIS_BUILD_DIR/Makefile .
          cat > all.config << 'EOF'
          CONFIG_COMPILE_TEST=y
          EOF
          for config in ${CONFIGS}; do
            echo ========== begin $config ==========
            make SRC=$TRAVIS_BUILD_DIR KCONFIG_ALLCONFIG=1 V=1 "$config"
            make SRC=$TRAVIS_BUILD_DIR TGT="\$(OBJ)/$config" V=1 all check
            or1k-linux-musl-size build/$config/scp.elf
            grep __bss_end build/$config/scp.map
            sha256sum -b build/$config/scp.bin
            echo =========== end $config ===========
          done
          make SRC=$TRAVIS_BUILD_DIR V=1 html
...
